# Use the official NGINX image as a parent image
FROM nginx

# Copy the default nginx.conf provided by the parent image
# This step is optional, you can provide your own nginx.conf if you prefer
COPY nginx.conf /etc/nginx/nginx.conf
