# call this with `docker-compose up`

version: '3'
services:
  web:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 8000
    depends_on:
      - nginx
  nginx:
    build: ./nginx
    ports:
      - 80:80
  send:
    build: ./send
    depends_on:
       - nginx
       - web